### ISSUE TITLE
Feedback so far

### ISSUE THREAD

**Issue by grumpygeek** [JustOff/moon-tester-tool#1]
It works on some (No Resource URI and Canvas Defender).  PM 27.1b2 20170117033508
It did not work on all that I tried, but I didn't keep a list.  Last one was: 
User Style Manager 1.2  (min 40.0, max 47.0)
I did get that to install (and appears to work) by editing min ver # in install.rdf just as I had done on ver 1.1.1 on PM 27.0.3.
No assistance needed, just thought I'd report it.  May add more later if you are interested.

**Comment by JustOff** [comment]
Please keep in mind that Moon Tester Tools does nothing but changes targetApplication to Pale Moon and min/maxVersion to 27.0/*. None of magical actions are not applied at all. The only benefit from Moon Tester Tools is the ability to simplify testing, no more, no less. 

If you find that particular version of particular addon works well, you can share this info at Pale Moon forum and/or write to author and ask him to support Pale Moon officially. Report something about it here does not make any sense.
