### ISSUE TITLE
Moon Tester Tool 2.1.0 Blocked/Disabled by PM 29.0.0

### ISSUE THREAD

**Issue by largrizzly** [JustOff/moon-tester-tool#10]
I just received a warning in PM that MTT 2.1.0 has been disabled.

**Comment by JustOff** [comment]
Page https://blocklist.palemoon.org/info/?id=pm116 states that 
```
This extension is insufficiently warning the user about harmful effects of
its use as a "compatibility fix" outside of testing/development environments.
```
I disagree with such a far-fetched rationale as all necessary warnings are clearly provided. 

To make MTT work again, you can disable the blocklist by setting `Add-on security level` to `Off` in `Preferences/Security`.

**Comment by jobbautista9** [comment]
Disabling the blocklist is not necessary. You can simply just enable the add-on again via the Add-ons Manager.

**Comment by JustOff** [comment]
Indeed, you are right, that is enough. Thanks for pointing this out!

**Comment by TPS** [comment]
Given the attitude change toward extensions in PM 29.2.x+, any idea whether this will still be able to be enabled, though blocked?

**Comment by JustOff** [comment]
You can still set `Add-on security level` to `Off` in `Preferences` on `Security` tab, but from tomorrow it will be the only option.

**Comment by largrizzly** [comment]
Will "extensions.blocklist.enabled", false still be an alternative to being able to install MTT? I have just a couple of FX extensions that may require the use of MTT after tomorrow.

**Comment by JustOff** [comment]
Yes, but you'd better do it using preferences as described above, as changing this setting via `about:config` doesn't always work correctly.

**Comment by largrizzly** [comment]
Thanks JustOff.  I have my pref set to OFF already. I'll try doing it the right way before messing with the "internals". Worse come to worse, I can always modify the install.rdf files in my FX extensions with the PM info, but MTT just makes it a lot easier!

**Comment by PotentialTumbleweed** [comment]
> 
> 
> Indeed, you are right, that is enough. Thanks for pointing this out!
> 
> UPD: This is no longer an option.

Hello, I see you closed this, but I want to ask for some clarification if I may. In the 29.2.0 version, we will not be able to enable MTT in the Add-ons Manager?

**Comment by JustOff** [comment]
Currently there is an inconsistency between the blocklist which comes with Pale Moon 29.2 and the one that is served from blocklist.palemoon.org. So in some cases it's still possible to enable MTT without turning off the blocklist, but this may change at any time.
