### ISSUE TITLE
Need to add support for Borealis Navigator and Iceape-UXP browsers

### ISSUE THREAD

**Issue by EgorKuzevanov** [JustOff/moon-tester-tool#11]
Hello, dear JustOff! Can you add support for [Borealis Navigator](https://o.rthost.win/boc-uxp/) and [Iceape-UXP](https://o.rthost.win/hbl-uxp/) browsers based on SeaMonkey 2.49.5 to the Moon Tester Tool extension? The fact is that under these browsers there are not enough good extensions (except perhaps uBlock Origin). And the old extensions for Firefox, SeaMonkey and Pale Moon do not work with the Borealis Navigator and Iceape-UXP browsers, and when trying to install them, errors pop up about the incompatibility of extensions. Thanks in advance.

**Comment by JustOff** [comment]
If one need such a tool for other browsers, they should create a separate add-on, like STT made for Basilisk.
