### ISSUE TITLE
Installed, enabled but no function

### ISSUE THREAD

**Issue by GaucheRabbit** [JustOff/moon-tester-tool#12]
v2.1.3 on Pale Moon v29.2.1

Just displays this in the add-on page:
https://images2.imgbox.com/27/a0/ctz8E9pq_o.png

The "select file" button is no longer present. Use to be there on older versions:
https://images2.imgbox.com/05/8f/hZiFLCKB_o.png

Did it move or something?
Add-on security is set to off.

**Comment by JustOff** [comment]
![2020-10-24_13-03-28](https://user-images.githubusercontent.com/340855/125559556-87ee70fe-cabf-4968-b0b7-0bd4c2c4ba0f.png)

**Comment by GaucheRabbit** [comment]
There it is. Thanks for the help.
