### ISSUE TITLE
Some extensions can't be installed

### ISSUE THREAD

**Issue by xlovinglyx** [JustOff/moon-tester-tool#13]
I still got mtt to work on pm29.1, only one file is missing.

I've read your efforts to try to make legacy extensions compatibles in pml
& the other shitbrain tobin calling u shitoff, which is so elegant from admins,
& his dumb moonwolf almost always trying to be
negative on ppl without ever contributing in extensions
& now killing legacy addons on pm 29.2.

i've still installed mtt to update at least half of my extensions i couldn't
find from palemoon. because from my experience, even if you warned
us, i've never had issues with your addons & works.

i'd like to still ask u an effort by trying to fix one or two of my addons over 15
that couldn't have mtt's tweak applied. it'd be kind of you if you could look
at those archive & try to tweak them manually, knowing mtt failed.

Attached zipped xpi's
[unupdated xpis.zip](https://github.com/JustOff/moon-tester-tool/files/6844561/unupdated.xpis.zip)

**Comment by xlovinglyx** [comment]
[That Xpi File.zip](https://github.com/JustOff/moon-tester-tool/files/6844393/That.Xpi.File.zip)

**Comment by xlovinglyx** [comment]
1 Question

Do i have to install pm 28.* to make mtt work ? i see no error in the tweaking process
using pm 29.1 but i also don't see any palemoon id in new rtfs

**Comment by xlovinglyx** [comment]
& no un buttons cant be updated (( 2 failed, no un is very important, i wish u could do something about it without affecting
pm's ui or functionality.

otherwise, all your fixes were applied & worked, i'm now on pm 29.3.0

**Comment by JustOff** [comment]
Try [moon-tester-tool-2.1.4b1.xpi](https://github.com/JustOff/moon-tester-tool/releases/download/2.1.3/moon-tester-tool-2.1.4b1.xpi).

Use a fresh XPI of `NoUn Buttons` from [Classic Add-ons Archive](https://github.com/JustOff/ca-archive), because your copy is corrupted.

**Comment by xlovinglyx** [comment]
You saved me from losses of precious extensions, nouns remains without the [test] mention but it's not an issue as 
the re-upgrade to 29.3 was successful & nouns is fully accepted )) & no extension at palemoon could get rid of dom storage.,
only minimal extension panel. Everything runs well, afterall, only minor tweaks had your test conversion. If people had a brain,
for all those that were affected by tobin's "aggressive" rejections of legacy addons while tolering them in the beginning, they would have given users a chance to keep running them with appropriate consciousness. They seem to be playing mozilla's tricks, when i know the status bar was massacred from firefox, & moonwolf trembles when people try to avoid links that generate ads .. .

You're an ace Justoff  ( ͡~ ͜ʖ ͡° )

thank you so much for saving me hours & days of mental confusion & headaches.

**Comment by JustOff** [comment]
Resolved in [2.1.4](https://github.com/JustOff/moon-tester-tool/releases/tag/2.1.4).
