### ISSUE TITLE
Doesn't allow to install "Close tabs to the left" extension

### ISSUE THREAD

**Issue by vlakoff** [JustOff/moon-tester-tool#2]
As discussed on [this topic on forum.palemoon.org](https://forum.palemoon.org/viewtopic.php?f=46&t=16390), the Tester Tool doesn't allow to install the [Close tabs to the left](https://addons.mozilla.org/en-US/firefox/addon/close-tabs-to-the-left/) extension. This issue is still present in the recently released version 1.0.6.

**Comment by JustOff** [comment]
Resolved by Moon Tester Tool 1.1.0.

**Comment by vlakoff** [comment]
I didn't know you were already aware of the issue. Thank you for fixing it!
