### ISSUE TITLE
Extensions Option Menu 2.18 won't install with MTT 1.10

### ISSUE THREAD

**Issue by graciecat** [JustOff/moon-tester-tool#3]
I tried to install [Extension Options Menu 2.18](https://addons.mozilla.org/en-US/firefox/addon/extension-options-menu/) with [Moon Tester Tool 1.10](https://addons.palemoon.org/addon/moon-tester-tool/), but it refused to install it, returning the same error we were getting with Close Tabs to the Left, that it wasn't compatible with Pale Moon.

For comparison, I installed [EOM 3.13](https://addons.mozilla.org/en-US/firefox/addon/extension-options-menu/versions/2.13.1-signed) using MTT. Version 3.13 has a FF version number low enough to install in PM 27, but the toolbar button won't appear without modification to the **chrome.manifest** . MTT *did* add the necessary line to chrome.manifest (as the button appeared), so that's good news, but it obviously didn't modify the **install.rdf** because the listing still has the orange button in the Add-ons Manager.

**Comment by graciecat** [comment]
BTW, you may ask, why don't I just use [url=https://addons.palemoon.org/addon/extension-preferences-menu/]Extension Preferences Menu[/url]? The main reason is that my favorite theme has a special toolbar button it uses for EOM, and it doesn't show up for EPM.
[button comparison]](url)
So I would like to see if maybe MTT can be modified?

**Comment by JustOff** [comment]
Resolved by MTT 1.1.2.
