### ISSUE TITLE
Port to SeaMonkey?

### ISSUE THREAD

**Issue by graciecat** [JustOff/moon-tester-tool#4]
Would it be possible for you to make a port of this excellent and useful extension to SeaMonkey? In particular there is a need to remove the "For Firefox only" sign and unlock downloads of incompatible extensions from AMO. 

There exists an web-based extension converter for SeaMonkey, but this is useless if we cannot download the files or access the URL for the XPI file. It would be great to have a Sea-Tester-Tool! (Or Monkey-Tester-Tool!)

**Comment by JustOff** [comment]
Porting Moon Tetser Tool to SeaMonkey would require to create and support a completely independent extension. Sorry, but I do not think it's worth the effort.

To remove the "For Firefox only" sign and unlock downloads of SeaMonkey-incompatible extensions from AMO you can install [Modify HTTP Response](https://addons.mozilla.org/addon/modify-http-response/) and use following filter:
```
[["addons.cdn.mozilla.net",["/impala-min\\.js/",["$(\"#downloadAnyway\").attr","return;$(\"#downloadAnyway\").attr"]]]]
```
