### ISSUE TITLE
Compatibility with Download Cleaner extension

### ISSUE THREAD

**Issue by vlakoff** [JustOff/moon-tester-tool#5]
Trying to install the [Download Cleaner](https://addons.mozilla.org/en-US/firefox/addon/download-cleaner/) extension, it is not installed, actually nothing happens.

<br> Also, I'm getting this error in the Browser Console:

> alert is not defined &nbsp;&nbsp; bootstrap.js:60:0

Which seems to be a bug revealed in [bootstrap.js](https://github.com/JustOff/moon-tester-tool/blob/5c930e18dcd628ea7ed1cab521445c8f11f01386/bootstrap.js#L60).

**Comment by JustOff** [comment]
I can't confirm this, Download Cleaner 1.6.0 installs just fine using MTT 1.1.2. Probably something is wrong with your profile, try on a clean one.

**Comment by vlakoff** [comment]
Mmm, I'm not encountering the error anymore (on the same profile, and on a fresh profile). Maybe some browser restart that was needed at some point.

Thus, not worth investigating further.
