### ISSUE TITLE
"Add to Pale Moon" appearing at AMO on extensions that still won't install

### ISSUE THREAD

**Issue by graciecat** [JustOff/moon-tester-tool#6]
I have MTT 1.1.4 installed in PM 27.6.0a1 x64 (2017-10-18). 

At the AMO page, MTT's modification to AMO styling gave me the **Add to Pale Moon** button for an add-on called [Pimpzilla](https://addons.mozilla.org/en-US/firefox/addon/pimpzilla/).  (It's listed in the Extensions pages, but it is acutally a Theme.)

![pimpzilla green button](https://user-images.githubusercontent.com/18286141/31862182-d63c80a6-b707-11e7-820f-5a1a453365a0.png)

But when I attempted to install it, PM told me it was incompatible.
![pimpzilla not compatible](https://user-images.githubusercontent.com/18286141/31862220-46a7d93a-b708-11e7-8305-e452fb24bcc8.png)

I was able to install it manually with the Moon Tester Tool. It looks terrible, but that's not the point. The issues is that the **Add to Pale Moon** buton appeared even though it wouldn't install.

I did notice that it is a JAR file rather than an XPI file, so I think that is the cause for the erroneous **Add to Pale Moon** button instead of the correct **Download** button.

**Comment by JustOff** [comment]
> The issues is that the Add to Pale Moon buton appeared even though it wouldn't install.

The style and text of the button is determined only on the basis of whether the version of the add-in is in a compatible range. MTT can't automagically guess the actual result of the installation.
