### ISSUE TITLE
[request] support for waterfox

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [JustOff/moon-tester-tool#7]
Hi there,

This might seem strange, but I'd like to check and see if some extensions will work with Waterfox and they're marked incompatible. 

I have tried changing the target ID and version numbers, looked a bit further and swapped out the ID in %pmdata or w/e. I don't really have any experience with it. :disappointed: 

One example that I wanted to try is https://addons.palemoon.org/addon/addons-manager-fix/ simply changing target ID and min/max wasn't good enough, still marked incompatible.

Appreciate your time.

**Comment by JustOff** [comment]
Pale Moon has its own application id, different than Firefox, and it uses rather strict compatibility restrictions for add-ons. MTT provides a way to workaround these things, but it has no magic inside, thus if an add-on is not compatible with the browser, it will not work in any case.

At the same time, Waterfox is almost identical to Firefox and even shares the application id, so no tester tools can be helpfull (remember: magic isn't included).

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@JustOff 

While I agree with you about it not being magic, it is worth noting that Waterfox is far from identical because it supports both XUL and webextensions, it doesn't enforce signing and allows for other plugins. You seem knowledgeable, I'm not sure if you knew that already, but I thought it was worth mentioning.

I realize there are clear differences from PM and WF that might not work together on some extensions. I think the problem for me was that I didn't change the right thing in the example I gave. Even if the extension doesn't work at all, it shouldn't be disabled and marked incompatible.

Maybe I misunderstood, but your tool is supposed to work the opposite way while providing the same result in PM, even if the extension is totally broken and breaks the browser, it will be installed and enabled. If MTT provides a way to work around those things by replacing those values in an extension to test it, could it not swap those same values on a PM extension to test it the same way? I know the extension could still be broken, but at least it could be tried.

I appreciate your time, thank you for your consideration.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I'm not sure I'm doing an effective job at communicating and or I'm not understanding. :8ball: 

What I'm saying is, not to swap extension values of firefox to waterfox, you're right, those are almost identical. Unfortunately now with ESR 60 out there is no more XUL support for any present or future FF releases.

What I'm asking is, if your extension can replace the values to make a FF legacy extension load, even if it is broken or makes the browser (PM) close, could it also do the opposite with a PM extension by replacing the PM values with WF values and load the resulting extension even if it breaks?

I only ask because I probably missed something when I tried to do it myself and was hoping maybe I could use this tool to try something similar, even if it were to fail.

Apologies for taking your time. 

Thanks

**Comment by JustOff** [comment]
> could it also do the opposite with a PM extension by replacing the PM values with WF values and load the resulting extension even if it breaks?

No, it can't, just because it's impossible.
