### ISSUE TITLE
Pale Moon won't allow activation of themes installed through this tool

### ISSUE THREAD

**Issue by Grafini** [JustOff/moon-tester-tool#8]
With Pale Moon 28, the checkCompatibility preference in about:config no longer works. Thus, if an extension reports itself to be incompatible, Pale Moon won't let it be activated.

For Moon Tester tool to continue to be useful, it will have to deactivate the compatibility check as well.

**Comment by JustOff** [comment]
MTT has never relied on the `checkCompatibility` preference, so nothing has changed with Pale Moon 28 on this matter. Thus, MTT still allows to install any extension or theme, regardless of target application and versions specified in its manifest.

However, this as before does not guarantee that this extension will work correctly, because MTT is designed for compatibility testing, and not for everyday use.

**Comment by Grafini** [comment]
Yes, extensions can still be _installed_ with this tool, but without something like the checkCompatibility  preference, the installed extension can't be _used_. Thus, without some way to reinstate that preference or something so that the extension can be used, I'm having a hard time figuring out the purpose of this extension. What's the point of forcing Pale Moon to install something, if you don't also force it to use the thing that's installed? I'm talking about some things that I know are compatible enough because they work when I edit the install.rdf.

**Comment by JustOff** [comment]
> Yes, extensions can still be installed with this tool, but without something like the checkCompatibility preference, the installed extension can't be used.

`checkCompatibility` was just another way to install extensions *without* MTT and has nothing to do with the possibility of using them.

> What's the point of forcing Pale Moon to install something, if you don't also force it to use the thing that's installed?

The point is to check whether it works or not, if the author of the extension has never tested it with Pale Moon and indicated the version of Firefox that does not allow it to be installed in Pale Moon. **There is no and never was a way to make the extension work if it is not consistent in fact.**

**Comment by JustOff** [comment]
> Pale Moon won't allow me activate anything I install with this tool because it thinks they're incompatible.

I don't know what do you mean by "activate".

> I think your addon could be much more useful if you'd integrate a way to disable the compatibility check.

There is no such thing as "compatibility check" after the extension was allowed to be installed.

**Comment by JustOff** [comment]
I don't see any themes installed using MTT on your screenshot, since none of them has "[FIX]" at the beginning of the name.
