### ISSUE TITLE
"Pure URL" not work as expected

### ISSUE THREAD

**Issue by Symbian9** [JustOff/moon-tester-tool#9]
I just install *Pure URL v1.2.6* (from CA-Archive), 

![pic.1](https://i.imgur.com/8kmOyib.png)

But it did NOT clear URL when I click any external links in posts on Facebook (`fbclid` already added in the garbage list)

**Comment by JustOff** [comment]
You should report this to the [Pure URL developer](http://veg.by/en/blog/category/firefox/).

**Comment by Symbian9** [comment]
May I use this issue for cast @vrubleg to solve this issue?
